// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://pzdqntoukujntcidqzyl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6ZHFudG91a3VqbnRjaWRxenlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM3OTMxMzcsImV4cCI6MjA4OTM2OTEzN30.ph_x73J9gzles74NsCsgdsevtVctpUugk8k-jHSxxUc";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);